### ISSUE TITLE
hash update

### ISSUE THREAD

**Issue by danny-source** [xogium/buildroot-stm32mp135d-odyssey#5]
pls check hash and update , tks

diff --git a/packages/bmi08x-src/bmi08x-src.hash b/packages/bmi08x-src/bmi08x-src.hash
index faa1db9..8618f82 100644
--- a/packages/bmi08x-src/bmi08x-src.hash
+++ b/packages/bmi08x-src/bmi08x-src.hash
@@ -1,2 +1,2 @@
 # Locally calculated
-sha256  6d63a806021e8cc534a42bdea56935d609ceb3d40f91ff8c93695b53574d3aad  bmi08x-src-bmi08x_v1.4.4.tar.gz
+sha256 b5adcf0877beddb61419e8b4e7581c8c2b52370537ae5c5ebf63e8a519f9510f  bmi08x-src-bmi08x_v1.4.4.tar.gz

**Comment by xogium** [comment]
Hi,
I will check this out today. Thank you for reporting!

Do we know why this might suddenly have changed?

**Comment by danny-source** [comment]
i don't have idea, maybe it  retag version?

**Comment by xogium** [comment]
Thanks for reporting, I will fix up the hash and investigate why it has 
changed, just in case something weird might be going on. I will comment 
on the issue as soon as I've put up a fix.

**Comment by xogium** [comment]
Hi @danny-source, I've just pushed a fix for the issue.
The proper fix in this case is to switch the download to a non-automatically generated tarball from github, as those often end up having changed hash checksum because they get regenerated. I've hence made it so the version is an actual commit hash, which should stabilize the version but also the hash checksum.

My testing shows this seems to work, but feel free to mention it here if you encounter any issue and I'll be happy to fix.
